### ISSUE TITLE
installation dosnt complete

### ISSUE THREAD

**Issue by nourBerro** [frappe/erpnext_vagrant#13]
when i try vagrant up the following issue is raised 
Downloading/unpacking honcho (from bench==4.1.0)
    default:   Downloading honcho-1.0.1-py2.py3-none-any.whl
    default: Downloading/unpacking python-crontab (from bench==4.1.0)
    default: Cleaning up...
    default: Exception:
    default: Traceback (most recent call last):
    default:   File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    default:     status = self.run(options, args)
    default:   File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    default:     requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
    default:   File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1198, in prepare_files
    default:     do_download,
    default:   File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1376, in unpack_url
    default:     self.session,
    default:   File "/usr/lib/python2.7/dist-packages/pip/download.py", line 582, in unpack_http_url
    default:     unpack_file(temp_location, location, content_type, link)
    default:   File "/usr/lib/python2.7/dist-packages/pip/util.py", line 643, in unpack_file
    default:     untar_file(filename, location)
    default:   File "/usr/lib/python2.7/dist-packages/pip/util.py", line 574, in untar_file
    default:     path = os.path.join(location, fn)
    default:   File "/usr/lib/python2.7/posixpath.py", line 80, in join
    default:     path += '/' + b
    default: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 19: ordinal not in range(128)
    default: Storing debug log for failure in /home/vagrant/.pip/pip.log

**Comment by bndn** [comment]
I have the same error on my Debian Jessie server (Python 2.7).
